[package]
name    = "cab-syntax"
version = "0.0.1"
edition = "2024"

[dependencies]
enumset           = "1.1.3"
log               = "0.4.21"
miette            = "7.4.0"
num               = "0.4.3"
num_enum          = "0.7.2"
peekmore          = "1.3.0"
rowan             = "0.16.1"
static_assertions = "1.1.0"
thiserror         = "2.0.11"

[dependencies.derive_more]
version  = "1.0.0"
features = [ "full" ]

[dependencies.phf]
version  = "0.11.3"
features = [ "macros" ]

[dependencies.yansi]
version  = "1.0.1"
features = [ "detect-env", "detect-tty", "hyperlink" ]
